=== silviadp/LenguajedeMarcas22-23/TEMA 1 INTRODUCCIÓN A LOS LENGUAJES DE MARCAS. XML/XML/XSD/ornitorrinca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="address">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="street" type="xs:string" />
                            <xs:element name="number" type="xs:string" />
                            <xs:element name="city" type="xs:string" />
                            <xs:element name="province" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="phone" maxOccurs="unbounded" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="dni" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== silviadp/LenguajedeMarcas22-23/TEMA 1 INTRODUCCIÓN A LOS LENGUAJES DE MARCAS. XML/XML/XSD/ornitorrinco.xml
<?xml version="1.0" encoding="UTF-8?"?>
<student dni="1234567A"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ornitorrinca.xsd">
    <name>JUAN</name>
    <address>
        <street>jfgiopjh</street>
        <number>5</number>
        <city>sevilla</city>
        <province>utrera</province>
    </address>
    <phone>723648734</phone>
    <phone>847239847</phone>
</student>
